#!/bin/sh
# Generate every build description from build/sources.txt.
#
# There is one source list and three build description formats, so the three
# cannot be allowed to drift apart by hand.  Two things differ from one
# implementation to the next, and the list carries a marker for each: @compat
# for members the build has to supply itself because the implementation lacks
# them, and @optional for the optional structures it provides.  Each is
# replaced by the file list of the profile being generated, from
# build/compat/ and build/optional/.  A profile with no list of its own in
# either directory falls back to none.txt there.
#
# Run from anywhere; writes into build/.
set -e
cd "$(dirname "$0")/.."

core=build/sources.txt

# list_for DIR PROFILE -- that profile's list, or the default if it has none.
list_for() {
  if [ -f "$1/$2.txt" ]; then echo "$1/$2.txt"; else echo "$1/none.txt"; fi
}

# insert FILE -- the file names in a profile list, comments and blanks dropped.
insert() {
  while IFS= read -r entry; do
    case "$entry" in ''|'#'*) continue ;; esac
    echo "$entry"
  done < "$1"
}

# expand PROFILE -- the source list with @compat and @optional replaced by
# that profile's files, comments and blank lines stripped.
expand() {
  profile=$1
  while IFS= read -r line; do
    case "$line" in
      ''|'#'*)     continue ;;
      '@compat')   insert "$(list_for build/compat "$profile")" ;;
      '@optional') insert "$(list_for build/optional "$profile")" ;;
      *)           echo "$line" ;;
    esac
  done < "$core"
}

banner() {
  echo "$1 Generated by tools/gen-builds.sh from build/sources.txt,"
  echo " * $(list_for build/compat "$2") and $(list_for build/optional "$2")."
  echo " * Edit those, not this file."
  echo " *"
}

gen_cm() {
  profile=$1; out=$2; heap=$3
  {
    banner "(*" "$profile"
    echo " * SML/NJ Compilation Manager.  Build with:"
    echo " *   ml-build $out Main.main $heap"
    echo " * then run the resulting heap image with sml @SMLload=..."
    echo " *)"
    echo "Group is"
    echo "  \$/basis.cm"
    expand "$profile" | sed 's|^|  ../|'
  } > "$out"
}

gen_mlb() {
  profile=$1; out=$2; tool=${3:-mlton}
  {
    banner "(*" "$profile"
    echo " * MLton / MLKit.  Build with:"
    echo " *   $tool -output basis-tests $out"
    echo " *)"
    echo "local"
    echo "  \$(SML_LIB)/basis/basis.mlb"
    echo "in"
    expand "$profile" | sed 's|^|  ../|'
    echo "  ../build/mlton-main.sml"
    echo "end"
  } > "$out"
}

gen_use() {
  profile=$1; out=$2
  {
    banner "(*" "$profile"
    echo " * Sequential loader for systems without a build manager (Poly/ML,"
    echo " * Moscow ML).  Run from the repository root:"
    echo " *"
    echo " *   poly --script $out"
    echo " *   poly --script $out -- --trials 50 --only List"
    echo " *)"
    expand "$profile" | sed 's|^\(.*\)$|use "\1";|'
    cat <<'TAIL'

(* Poly/ML passes its own command line through CommandLine.arguments, script
 * name and all, so only what follows a -- separator is meant for the suite. *)
val () =
  let
    fun afterSeparator [] = []
      | afterSeparator ("--" :: rest) = rest
      | afterSeparator (_ :: rest) = afterSeparator rest
  in
    (* Exit with the run's own status, as the other two loaders do.  A script
     * that always succeeds cannot be used to gate anything. *)
    OS.Process.exit (Main.runWith (afterSeparator (CommandLine.arguments ())))
  end;
TAIL
  } > "$out"
}

# The portable descriptions name no optional structure, so they compile
# anywhere; the per-implementation ones add what that implementation has.
gen_cm  none   build/sources.cm         basis-tests
gen_mlb none   build/sources.mlb
gen_use none   build/load.sml

gen_cm  smlnj  build/sources-smlnj.cm   basis-tests
gen_mlb mlton  build/sources-mlton.mlb
gen_mlb mlkit  build/sources-mlkit.mlb  mlkit
gen_use polyml build/load-polyml.sml

echo "wrote build/sources.cm build/sources.mlb build/load.sml"
echo "      build/sources-smlnj.cm build/sources-mlton.mlb build/sources-mlkit.mlb"
echo "      build/load-polyml.sml"
