#!/bin/sh
# Generate every build description from build/sources.txt.
#
# There is one source list and three build description formats, so the three
# cannot be allowed to drift apart by hand.  Since the optional structures a
# build may name differ from one implementation to the next, the list also
# carries an @optional marker, which is replaced by the file list of the
# profile being generated -- see build/optional/.
#
# Run from anywhere; writes into build/.
set -e
cd "$(dirname "$0")/.."

core=build/sources.txt

# expand PROFILE -- the source list with @optional replaced by that profile's
# files, comments and blank lines stripped.
expand() {
  profile=$1
  while IFS= read -r line; do
    case "$line" in
      ''|'#'*) continue ;;
      '@optional')
        while IFS= read -r opt; do
          case "$opt" in ''|'#'*) continue ;; esac
          echo "$opt"
        done < "build/optional/$profile.txt"
        ;;
      *) echo "$line" ;;
    esac
  done < "$core"
}

banner() {
  echo "$1 Generated by tools/gen-builds.sh from build/sources.txt and"
  echo " * build/optional/$2.txt.  Edit those, not this file."
  echo " *"
}

gen_cm() {
  profile=$1; out=$2; heap=$3
  {
    banner "(*" "$profile"
    echo " * SML/NJ Compilation Manager.  Build with:"
    echo " *   ml-build $out Main.main $heap"
    echo " * then run the resulting heap image with sml @SMLload=..."
    echo " *)"
    echo "Group is"
    echo "  \$/basis.cm"
    expand "$profile" | sed 's|^|  ../|'
  } > "$out"
}

gen_mlb() {
  profile=$1; out=$2
  {
    banner "(*" "$profile"
    echo " * MLton / MLKit.  Build with:"
    echo " *   mlton -output basis-tests $out"
    echo " *)"
    echo "local"
    echo "  \$(SML_LIB)/basis/basis.mlb"
    echo "in"
    expand "$profile" | sed 's|^|  ../|'
    echo "  ../build/mlton-main.sml"
    echo "end"
  } > "$out"
}

gen_use() {
  profile=$1; out=$2
  {
    banner "(*" "$profile"
    echo " * Sequential loader for systems without a build manager (Poly/ML,"
    echo " * Moscow ML).  Run from the repository root:"
    echo " *"
    echo " *   poly --script $out"
    echo " *   poly --script $out -- --trials 50 --only List"
    echo " *)"
    expand "$profile" | sed 's|^\(.*\)$|use "\1";|'
    cat <<'TAIL'

(* Poly/ML passes its own command line through CommandLine.arguments, script
 * name and all, so only what follows a -- separator is meant for the suite. *)
val () =
  let
    fun afterSeparator [] = []
      | afterSeparator ("--" :: rest) = rest
      | afterSeparator (_ :: rest) = afterSeparator rest
  in
    (* Exit with the run's own status, as the other two loaders do.  A script
     * that always succeeds cannot be used to gate anything. *)
    OS.Process.exit (Main.runWith (afterSeparator (CommandLine.arguments ())))
  end;
TAIL
  } > "$out"
}

# The portable descriptions name no optional structure, so they compile
# anywhere; the per-implementation ones add what that implementation has.
gen_cm  none   build/sources.cm         basis-tests
gen_mlb none   build/sources.mlb
gen_use none   build/load.sml

gen_cm  smlnj  build/sources-smlnj.cm   basis-tests
gen_mlb mlton  build/sources-mlton.mlb
gen_use polyml build/load-polyml.sml

echo "wrote build/sources.cm build/sources.mlb build/load.sml"
echo "      build/sources-smlnj.cm build/sources-mlton.mlb build/load-polyml.sml"
